"""Write the findings of all analyses, with the real numbers, into docs/ANALYSES.md.

Connects as app_readonly, the web app's role, so the published numbers come through the
same privileges as the dashboard: aggregate views only, small cells already suppressed.
The output depends only on the data (no timestamps), so re-running on the same data gives
an identical file.

Usage (full dataset loaded):  py -3.12 scripts/export_findings.py
"""

from decimal import Decimal

from psycopg import sql

from common import REPO_ROOT, connect
from refresh_views import list_analyses

DOC = REPO_ROOT / "docs" / "ANALYSES.md"
BEGIN, END = "<!-- BEGIN findings (generated) -->", "<!-- END findings -->"
NOT_COUNTS = {"sort_order", "period", "cost_rank"}   # row labels, not counts


def fmt(value) -> str:
    if value is None:
        return "*suppressed*"
    if isinstance(value, bool):
        return "yes" if value else ""
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, Decimal):
        return f"{value:,.2f}" if value.as_tuple().exponent == -2 else f"{value:,}"
    return str(value).replace("|", "\\|")


def check_no_small_cells(view: str, columns: list[str], rows: list[tuple]) -> None:
    # Last line of defence before publishing: never write a count from 1 to 10.
    for row in rows:
        for col, value in zip(columns, row, strict=True):
            if col not in NOT_COUNTS and type(value) is int and 1 <= value <= 10:
                raise SystemExit(f"Refusing to publish: {view}.{col} = {value} (small cell)")


def markdown_table(columns: list[str], rows: list[tuple]) -> str:
    lines = ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def build_section() -> str:
    parts = [BEGIN, "_Generated by `scripts/export_findings.py` from the full dataset. "
                    "Do not edit by hand._", ""]
    with connect("app") as conn:
        ref = conn.execute("SELECT reference_date FROM reporting.dataset_info").fetchone()[0]
        parts.append(f"**Reference date:** {ref} (latest encounter in the data). "
                     "\"Last 12 months\" means after "
                     f"{ref.replace(year=ref.year - 1)} up to and including {ref}.")
        parts.append("Counts from 1 to 10, and any figure that would reveal one, show as "
                     "*suppressed* (CMS cell-size policy).\n")
        for a in list_analyses():
            cur = conn.execute(sql.SQL("SELECT * FROM {} ORDER BY sort_order").format(
                sql.Identifier("reporting", a.view)))
            columns = [d.name for d in cur.description]
            rows = cur.fetchall()
            check_no_small_cells(a.view, columns, rows)
            keep = [i for i, c in enumerate(columns) if c != "sort_order"]
            parts += [
                f"### {a.header['Title']}",
                "",
                f"**Question:** {a.header['Question']}",
                "",
                f"SQL: [`sql/analyses/{a.path.name}`](../sql/analyses/{a.path.name}) · "
                f"view `reporting.{a.view}`",
                "",
                markdown_table([columns[i] for i in keep], [[r[i] for i in keep] for r in rows]),
                "",
                f"**Limitations:** {a.header['Limitations']}",
                "",
            ]
    parts.append(END)
    return "\n".join(parts)


def main() -> None:
    section = build_section()
    doc = DOC.read_text(encoding="utf-8")
    if BEGIN in doc:
        doc = doc[: doc.index(BEGIN)] + section + doc[doc.index(END) + len(END):]
    else:
        # Put the findings before the index benchmark section.
        marker = "## Index benchmark"
        head, _, tail = doc.partition(marker)
        doc = head + "## Findings\n\n" + section + "\n\n" + marker + tail
    DOC.write_text(doc, encoding="utf-8", newline="\n")
    print(f"Wrote findings for {len(list_analyses())} views to {DOC.relative_to(REPO_ROOT)}.")


if __name__ == "__main__":
    main()
